[package]
name = "indy-crypto-fuzz-target"
version = "0.1.0"
authors = ["Dave Huseby <dhuseby@linuxfoundation.org>"]

[dependencies]
afl = "0.2"

[dependencies.indy-crypto]
git = "https://github.com/dhuseby/indy-crypto.git"
branch = "fuzz"
default-features = false
features = [ "pair_amcl" ]
